# workflow to build binary files
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: build-binary-files

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: dhc_1.0.tgz
            asset_name: dhc-macos-amd64
    steps:
      - name: Build files
        run: |
          ## --------------------------------------------------------------------
          echo "Building binaries..."
          echo "$PWD"
          cd ..
          echo "$PWD"
          R CMD INSTALL --build ./dh-r-experiments